import { AddTaskModal } from "@/components/modals/add-task-modal";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AddColumnModal } from "@/components/modals/add-column-modal";
import { ThemeProvider } from "@/components/theme-provider";
import Link from "next/link";
import { Home } from "lucide-react";
import { CreateProjectModal } from "@/components/modals/create-project-modal";
import { AddPaymentModal } from "@/components/modals/add-payment-modal";
import { EditProjectModal } from "@/components/modals/edit-project-modal";
import { AddMemberModal } from "@/components/modals/add-member-modal";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className}`}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <AddTaskModal />
          <AddColumnModal />
          <CreateProjectModal />
          <AddPaymentModal />
          <AddMemberModal />
          <Toaster />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
