import { AddTaskModal } from "@/components/modals/add-task-modal";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AddColumnModal } from "@/components/modals/add-column-modal";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className}`}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <AddTaskModal />
          <AddColumnModal />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
